version: "3.2"
services:
  db:
    container_name: hedgehog_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5433:5432
    volumes:
      - ../postgres-data:/var/lib/postgresql-hedgehog/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
